version: '3.8'

services:
  frontend:
    build:
      context: ./system-monitor-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./system-monitor-server/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount host system directories for monitoring
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - /bin:/host/bin:ro
      - /:/host:ro
    privileged: true
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  frontend_data:
  backend_data: